### ISSUE TITLE
Double separators for apps that don't have quicklists before using ubuntu-recentquicklists

### ISSUE THREAD

**Issue by hotice** [thirschbuechler/ubuntu-recentquicklists#13]
For applications that don't have any quicklists prior to using ubuntu-recentquicklists (examples include: Vivaldi browser, Atom text editor, Image Viewer aka Eye Of GNOME, etc.), two separators are displayed between the recent quicklists and the app name:

![image](https://cloud.githubusercontent.com/assets/325449/17325916/d7ff859c-58b6-11e6-94d0-2158f7db7503.png)

**Comment by thirschbuechler** [comment]
yeah, I know.. this exists because per default, a seperator is added after each quicklist, to seperate the quicklist from the actions of the corresponding launcher (i.e. "new document").
Pssive programs such as viewers typically don't have actions, and therefore the seperator shouldn't be there.

For now, you may add rules for programs where this bug exists to the code of `ubuntu-recentquicklists.py`, around the lines `370-380`.

I think that can be checked in the `/usr/share/applications` folder, whether the launcher in question has the properties `X-Ayatana-Desktop-Shortcuts=`, so automation seems possible.

**Comment by thirschbuechler** [comment]
[fixed](https://github.com/thirschbuechler/ubuntu-recentquicklists/pull/15)
