### ISSUE TITLE
Check version?

### ISSUE THREAD

**Issue by orschiro** [thirschbuechler/ubuntu-recentquicklists#25]
Dear @thirschbuechler,

The more I use it, the more I love your program. 

Thank you so much!

One question:

How can I check from the terminal if I use the most recent version?

Thankfully,

-Robert

**Comment by thirschbuechler** [comment]
Hello Robert, nice to hear!

I don't know when I've put it in, but at least since V1.2.2 this feature exists:
The terminal output should contain `Ubuntu-recentquicklists V1.2.2 startup`

(The version is also shown on startup as notification bubble (usually top right corner), 
but you always can open `ubuntu-recentquicklists.py` as text file ("display" on doubleclick) and do a Crtl+F (search) for "Version".)

Cheers, Thomas

**Comment by orschiro** [comment]
Thank you, Thomas! :-)

However, I found it confusing to update. 

Why doesn't `./update.sh` just update?

```
orschiro@x230:~/ubuntu-recentquicklists$ ./update.sh 
---------------------------------------------
--Ubuntu-Recentquicklists V1.2 Update--
---------------------------------------------
Do you wish to update this program?
(This will grab the config-file urq.conf,
after that you can proceed with unistall.sh, then install.sh
1) Yes
2) No
#? 1
cp: '/home/orschiro/ubuntu-recentquicklists/urq.conf' and 'urq.conf' are the same file
```

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/19028811/76011fc6-8940-11e6-8694-d8ea2c2aa36d.png)

**Comment by thirschbuechler** [comment]
Well, you have to download the newest version and run `update.sh` from the extracted folder, and follow the instructions. (the `cp` command reports an error because you haven't followed the instructions and uninstalled, so there's still stuff there)

(I didn't check whether it's possible to just fetch the newest release branch via the `git clone` command
(certainly for the main branch, but that's not what I want it to do). If anyone wants to contribute that as an option for `update.sh`, I'll test and merge it)

`Update.sh` copies the config-file `urq.conf` into the current tmp installation folder from where you've run it (settings and pinned files), then when you run `install.sh` it takes everything in that folder (including `urq.conf`, as well as the in-folder version of the program) and puts it where it belongs.

regards

**Comment by orschiro** [comment]
I see, thanks!

Can I also simply download the latest version of `ubuntu-recentquicklists.py` and overwrite the same file in `~/ubuntu-recentquicklists` while keeping all the other files the same?

-Robert

**Comment by thirschbuechler** [comment]
Yes, you can, ideally also take log3.py
(I don't think I've made any changes to that, however)

regards

**Comment by orschiro** [comment]
Perfect, thanks!

That's easier for me to update. 

-Robert
